name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dist_sh_develop:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.38"

    runs-on: ubuntu-latest

    container:
      image: perl:${{ matrix.perl-version }}-threaded

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cache
        uses: actions/cache@v3
        with:
          path: local/
          key: cpm-ci-dist-sh-develop-${{ matrix.perl-version }}-${{ runner.os }}-${{ hashFiles('cpanfile') }}

      - name: Use local Perl packages
        run: |
          echo "$GITHUB_WORKSPACE/local/bin" | tee -a $GITHUB_PATH
          echo "PERL5LIB=$GITHUB_WORKSPACE/local/lib/perl5" | tee -a $GITHUB_ENV

      - name: Install cpm
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install --color --no-test App::cpm

      - name: Install required dependencies
        run: cpm install --color --no-test --with-configure --with-recommends --with-suggests

      - name: Install develop dependencies
        run: cpm install --color --no-test --with-develop

      - name: Install fatpack dependencies
        run: cpm install --color --no-test --feature=fatpack

      - name: Reinstall fatpack dependencies
        run: cpm install --color --no-test --reinstall if parent Exporter HTTP::Date HTTP::Status HTTP::Tiny IO::Socket::IP Module::Load Time::Local Try::Tiny

      - name: Make distribution
        run: ./Dist.SH

      - name: Make fatpack
        run: ./fatpack/fatpack.sh

  dist_sh:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"

    runs-on: ubuntu-latest

    container:
      image: perl:${{ matrix.perl-version }}-threaded

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cache
        uses: actions/cache@v3
        with:
          path: local/
          key: cpm-ci-dist-sh-${{ matrix.perl-version }}-${{ runner.os }}-${{ hashFiles('cpanfile') }}

      - name: Use local Perl packages
        run: |
          echo "$GITHUB_WORKSPACE/local/bin" | tee -a $GITHUB_PATH
          echo "PERL5LIB=$GITHUB_WORKSPACE/local/lib/perl5" | tee -a $GITHUB_ENV

      - name: Install cpm
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install --color --no-test App::cpm

      - name: Install required dependencies
        run: cpm install --color --no-test --with-configure --with-recommends --with-suggests

      - name: Make distribution
        run: ./Dist.SH
        env:
          TEST_SKIP_DEVELOP: "1"
